workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURSE == "merge_request_event" || $CI_COMMIT_BRANCH  == "main" || $CI_COMMIT_BRANCH  == "dev"
      when: always
    - when: never

stages: # List of stages for jobs, and their order of execution
  - push_into_walcaldeploy

push_into_walcaldeploy:
  image: ubuntu:latest
  stage: push_into_walcaldeploy
  script:
    - apt update -y && apt install git -y
    - git config --global user.email "cawsonoliver33@gmail.com"
    - git config --global user.name "Oliver Cawson"
    - git clone https://cawsonoliver33:$ACCESS_TOKEN@gitlab.com/i2xo/walcaldeploy
    - cd walcaldeploy/
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        git checkout main
      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        git checkout dev
      fi
    - git submodule update --remote --init
    - git add .
    - |
      if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
        git commit -m "update submodule on main"
      elif [[ "$CI_COMMIT_BRANCH" == "dev" ]]; then
        git commit -m "update submodule on dev"
      fi
    - git push
